name: Run master script

on:
  #schedule:
    # A cada hora
    # - cron: '0 * * * *'

  workflow_dispatch:
    inputs:
      playlist_url:
        description: 'YouTube playlist URL'
        required: true

jobs:
  run-master:
    runs-on: ubuntu-20.04

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Configure python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: "Install dependencies"
      run: pip install -r requirements.txt

    - name: "Install ffmpeg"
      run: sudo apt-get install ffmpeg

    - name: "Run project"
      run: python master.py
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        GOOGLE_DRIVE_CLIENT_ID: ${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}
        GOOGLE_DRIVE_PUBLIC_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_PUBLIC_FOLDER_ID }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        GOOGLE_DRIVE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_JSON }}
